#!/usr/bin/env python3
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
"""Assert that built wheels carry the license files they are required to carry.

A wheel bundles a compiled extension module that statically links every Rust
dependency, so it redistributes those dependencies and must ship their license
texts, plus the notices that Apache-2.0 section 4(d) requires it to relay. The
texts go in THIRD-PARTY-LICENSES and the notices are appended to NOTICE, both
generated by `dev/release/dependencies.sh generate-third-party-licenses`.

Neither failure mode is loud on its own: `[tool.maturin] include` and
`[project] license-files` are both glob-based, so a rename or a missing
generated file drops the texts without failing the build, and a wheel built
without running the generator quietly ships the plain project NOTICE. This
check makes both loud.

The files are generated per target, so a third failure mode is a wheel carrying
another platform's report. Passing the report name asserts against that: the
name is recorded in the header of both LICENSE and THIRD-PARTY-LICENSES.

Usage: check_wheel_licenses.py <directory containing wheels> [report name]
"""

import sys
import zipfile
from pathlib import Path

# Each entry must appear in every wheel, either at the wheel root or under
# `*.dist-info/licenses/`.
REQUIRED = ("LICENSE", "NOTICE", "THIRD-PARTY-LICENSES")

# A wheel whose THIRD-PARTY-LICENSES is this small is not a real license bundle;
# it is almost certainly a stub or a truncated file.
MIN_THIRD_PARTY_LICENSES_BYTES = 10_000

# Apache-2.0 section 4(d) notices are relayed in NOTICE, under this heading. A
# wheel carrying only the plain project NOTICE means the generator did not run,
# so the notices of the bundled dependencies are missing. Keep in sync with
# NOTICE_RELAY_HEADING in dev/release/dependencies.sh.
NOTICE_RELAY_HEADING = b"Bundled dependency notices"

# LICENSE gains a pointer to the license-text bundle. Keep in sync with
# LICENSE_APPENDIX_HEADING in dev/release/dependencies.sh.
LICENSE_APPENDIX_HEADING = b"Bundled third-party components"

# Files whose header names the wheel the report was generated for.
TARGETED = ("LICENSE", "THIRD-PARTY-LICENSES")


def check_wheel(path: Path, report: str | None) -> list[str]:
    errors = []
    with zipfile.ZipFile(path) as wheel:
        names = {name.rsplit("/", 1)[-1]: name for name in wheel.namelist()}
        for required in REQUIRED:
            if required not in names:
                errors.append(f"{path.name}: missing {required}")
                continue
            size = wheel.getinfo(names[required]).file_size
            if size == 0:
                errors.append(f"{path.name}: {required} is empty")
        bundle = names.get("THIRD-PARTY-LICENSES")
        if bundle is not None:
            size = wheel.getinfo(bundle).file_size
            if 0 < size < MIN_THIRD_PARTY_LICENSES_BYTES:
                errors.append(
                    f"{path.name}: THIRD-PARTY-LICENSES is only {size} bytes; "
                    "regenerate it with 'make generate-third-party-licenses'"
                )
        notice = names.get("NOTICE")
        if notice is not None and NOTICE_RELAY_HEADING not in wheel.read(notice):
            errors.append(
                f"{path.name}: NOTICE does not relay the notices of bundled "
                "dependencies; stage the generated files with "
                "'dev/release/dependencies.sh stage-third-party-licenses <report>'"
            )
        license_ = names.get("LICENSE")
        if license_ is not None and LICENSE_APPENDIX_HEADING not in wheel.read(
            license_
        ):
            errors.append(
                f"{path.name}: LICENSE does not point at THIRD-PARTY-LICENSES; "
                "stage the generated files with "
                "'dev/release/dependencies.sh stage-third-party-licenses <report>'"
            )
        if report is not None:
            # Substring, not equality: the header line reads `Wheel: <report>`,
            # and LICENSE names it in a sentence.
            expected = report.encode()
            for name in TARGETED:
                member = names.get(name)
                if member is not None and expected not in wheel.read(member):
                    errors.append(
                        f"{path.name}: {name} was not generated for "
                        f"{report}; this wheel carries another platform's report"
                    )
    return errors


def main() -> int:
    if not 2 <= len(sys.argv) <= 3:
        print(__doc__, file=sys.stderr)
        return 2

    dist = Path(sys.argv[1])
    report = sys.argv[2] if len(sys.argv) == 3 else None
    wheels = sorted(dist.glob("*.whl"))
    if not wheels:
        print(f"No wheels found in {dist}", file=sys.stderr)
        return 1

    errors = []
    for wheel in wheels:
        errors.extend(check_wheel(wheel, report))

    if errors:
        for error in errors:
            print(f"ERROR: {error}", file=sys.stderr)
        return 1

    for wheel in wheels:
        print(f"OK: {wheel.name} bundles {', '.join(REQUIRED)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
